load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.platform.util.trove",
    srcs = ["src"],
    iml_files = ["intellij.platform.util.trove.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    jvm_target = "7",
    visibility = ["//visibility:public"],
    exports = ["//m2:trove"],
    deps = ["//m2:trove"],
)
