load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "kotlin.code-insight.descriptions",
    iml_files = ["kotlin.code-insight.descriptions.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    resources = ["resources-en"],
    visibility = ["//visibility:public"],
    deps = ["//intellij-community/plugins/kotlin/base/frontend-agnostic:kotlin.base.frontend-agnostic[module]"],
)
