load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.python.community.plugin",
    iml_files = ["intellij.python.community.plugin.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    resources = ["resources"],
    visibility = ["//visibility:public"],
    deps = ["//intellij-community/platform/lang-api:intellij.platform.lang[module]"],
)
