load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.platform.util.rt.java8",
    srcs = ["src"],
    iml_files = ["intellij.platform.util.rt.java8.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    jvm_target = "8",
    visibility = ["//visibility:public"],
    deps = ["//intellij-community:jetbrains-annotations"],
)
