load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.maven.artifactResolver.common",
    srcs = ["src"],
    iml_files = ["intellij.maven.artifactResolver.common.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    jvm_target = "7",
    visibility = ["//visibility:public"],
    deps = ["//m2:org.apache.maven_maven-artifact_3.0.5"],
)
