load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.java.debugger.agent.holder",
    iml_files = ["intellij.java.debugger.agent.holder.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    visibility = ["//visibility:public"],
    deps = ["//m2:debugger-agent"],
)
