load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.platform.icons",
    iml_files = ["intellij.platform.icons.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    resources = ["src"],
    visibility = ["//visibility:public"],
)
