load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "kotlin.compiler-plugins.android-extensions-stubs",
    srcs = ["src"],
    iml_files = ["kotlin.compiler-plugins.android-extensions-stubs.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    visibility = ["//visibility:public"],
)
