load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.platform.lvcs",
    srcs = ["src"],
    iml_files = ["intellij.platform.lvcs.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    visibility = ["//visibility:public"],
    deps = ["//intellij-community/platform/core-api:intellij.platform.core[module]"],
)
