load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "generate-tostring",
    srcs = ["src"],
    iml_files = ["generate-tostring.iml"],
    test_srcs = ["testSrc"],
    visibility = ["//visibility:public"],
)
