load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.maven.model",
    srcs = ["src/main/java"],
    iml_files = ["intellij.maven.model.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    jvm_target = "7",
    resources = ["src/main/resources"],
    visibility = ["//visibility:public"],
    deps = ["//intellij-community:jetbrains-annotations-java5"],
)
