load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.platform.vcs.log.impl",
    # do not sort: must match IML order
    srcs = [
        "src",
        "gen",
    ],
    iml_files = ["intellij.platform.vcs.log.impl.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    resources = ["resources"],
    test_srcs = ["test"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "//intellij-community/platform/core-api:intellij.platform.core[module]",
        "//intellij-community/platform/vcs-log/api:intellij.platform.vcs.log[module]",
        "//intellij-community/platform/vcs-api:intellij.platform.vcs[module]",
        "//intellij-community/platform/vcs-log/graph:intellij.platform.vcs.log.graph.impl[module]",
        "//intellij-community/platform/platform-impl:intellij.platform.ide.impl[module]",
        "//intellij-community/platform/vcs-impl:intellij.platform.vcs.impl[module]",
        "//intellij-community:Guava",
        "//intellij-community:JUnit4[test]",
        "//intellij-community/platform/lang-impl:intellij.platform.lang.impl[module]",
        "//intellij-community/platform/vcs-log/graph-api:intellij.platform.vcs.log.graph[module]",
        "//intellij-community/platform/testFramework:intellij.platform.testFramework[module, test]",
        "//intellij-community:kotlin-stdlib[test]",
        "//intellij-community:kotlin-test[test]",
        "//intellij-community/platform/vcs-tests:intellij.platform.vcs.testFramework[module, test]",
        "//intellij-community/platform/util:intellij.platform.util[module]",
        "//intellij-community:assertJ[test]",
        "//intellij-community:miglayout-swing",
        "//intellij-community/platform/diff-impl:intellij.platform.diff.impl[module]",
        "//intellij-community/platform/statistics:intellij.platform.statistics[module]",
        "//intellij-community:fastutil-min",
        "//intellij-community/platform/core-ui:intellij.platform.core.ui[module]",
        "//intellij-community:gson",
        "//intellij-community:caffeine",
        "//intellij-community:kotlinx-coroutines-core",
        "//intellij-community:kotlinx-coroutines-guava",
        "//intellij-community/platform/diagnostic/telemetry:intellij.platform.diagnostic.telemetry[module]",
        "//intellij-community:opentelemetry",
        "//intellij-community/platform/sqlite:intellij.platform.sqlite[module]",
        "//intellij-community/platform/diagnostic/telemetry-impl:intellij.platform.diagnostic.telemetry.impl[module]",
        "//intellij-community/platform/backend/observation:intellij.platform.backend.observation[module]",
    ],
)
