load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.java.jshell.protocol",
    srcs = ["src"],
    iml_files = ["intellij.java.jshell.protocol.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    jvm_target = "9",
    test_srcs = ["testStrc"],
    visibility = ["//visibility:public"],
    deps = ["//intellij-community:JUnit4[test]"],
)
