load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.platform.util.tests",
    iml_files = ["intellij.platform.util.tests.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "//intellij-community/platform/util:intellij.platform.util[module, test]",
        "//intellij-community:kotlin-stdlib[test]",
        "//intellij-community:assertJ[test]",
        "//intellij-community:JUnit4[test]",
        "//intellij-community:jna[test]",
        "//intellij-community/platform/core-api:intellij.platform.core[module, test]",
        "//intellij-community/platform/projectModel-impl:intellij.platform.projectModel.impl[module, test]",
        "//intellij-community:jetCheck[test]",
        "//intellij-community:commons-compress[test]",
        "//intellij-community:Guava[test]",
        "//intellij-community/platform/testFramework:intellij.platform.testFramework[module, test]",
        "//intellij-community/platform/testFramework/extensions:intellij.platform.testExtensions[module, test]",
        "//intellij-community:memoryfilesystem[test]",
        "//intellij-community/platform/util-class-loader:intellij.platform.util.classLoader[module, test]",
        "//intellij-community:fastutil-min[test]",
        "//intellij-community/platform/platform-util-io:intellij.platform.ide.util.io[module, test]",
        "//intellij-community/platform/util-ex:intellij.platform.util.ex[module, test]",
        "//intellij-community/platform/util/diff:intellij.platform.util.diff[module, test]",
        "//intellij-community:JUnit5[test]",
        "//intellij-community/platform/util/jdom:intellij.platform.util.jdom[module, test]",
        "//intellij-community/platform/boot:intellij.platform.boot[module, test]",
        "//intellij-community/platform/testFramework/junit5:intellij.platform.testFramework.junit5[module, test]",
        "//intellij-community:kotlinx-coroutines-debug",
        "//intellij-community/tools/intellij.tools.ide.metrics.benchmark[module, test]",
    ],
)
