load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "kotlin.code-insight.structural-search-k2.tests",
    iml_files = ["kotlin.code-insight.structural-search-k2.tests.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    test_srcs = ["test"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "//intellij-community:kotlinc.kotlin-compiler-common[test]",
        "//intellij-community/platform/structuralsearch:intellij.platform.structuralSearch[module, test]",
        "//intellij-community/platform/testFramework:intellij.platform.testFramework[module, test]",
        "//intellij-community/java/testFramework:intellij.java.testFramework[module, test]",
        "//intellij-community/java/idea-ui:intellij.java.ui[module, test]",
        "//intellij-community/java/openapi:intellij.java[module, test]",
        "//intellij-community/plugins/kotlin/test-framework:kotlin.test-framework[module, test]",
        "//intellij-community/plugins/kotlin/tests-common:kotlin.tests-common[module, test]",
        "//intellij-community/plugins/kotlin/base/util:kotlin.base.util[module, test]",
        "//intellij-community/plugins/kotlin/code-insight/structural-search-k2:kotlin.code-insight.structural-search-k2[module, test]",
        "//intellij-community/plugins/kotlin/fir:kotlin.fir[module, test]",
    ],
)
