load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.jvm.analysis.java.tests",
    iml_files = ["intellij.jvm.analysis.java.tests.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    test_srcs = ["testSrc"],
    visibility = ["//visibility:public"],
    deps = ["//intellij-community/jvm/jvm-analysis-internal-testFramework:intellij.jvm.analysis.internal.testFramework[module, test]"],
)
