load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "kotlin.project-wizard.gradle",
    srcs = ["src"],
    iml_files = ["kotlin.project-wizard.gradle.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    resources = ["resources"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "//intellij-community:kotlin-stdlib",
        "//intellij-community/plugins/kotlin/base/frontend-agnostic:kotlin.base.frontend-agnostic[module]",
        "//intellij-community/plugins/kotlin/project-wizard/core:kotlin.project-wizard.core[module]",
        "//intellij-community/plugins/kotlin/project-wizard/idea:kotlin.project-wizard.idea[module]",
        "//intellij-community/platform/platform-impl:intellij.platform.ide.impl[module]",
        "//intellij-community/plugins/gradle:intellij.gradle.common[module]",
        "//intellij-community/platform/lang-core:intellij.platform.lang.core[module]",
        "//intellij-community/plugins/gradle/java:intellij.gradle.java[module]",
        "//intellij-community/java/idea-ui:intellij.java.ui[module]",
        "//intellij-community/platform/lang-impl:intellij.platform.lang.impl[module]",
        "//intellij-community/plugins/kotlin/base/plugin:kotlin.base.plugin[module]",
        "//intellij-community/java/openapi:intellij.java[module]",
        "//intellij-community/plugins/kotlin/gradle/code-insight-common:kotlin.gradle.code-insight-common[module]",
        "//intellij-community/plugins/kotlin/project-configuration:kotlin.project-configuration[module]",
        "//intellij-community/plugins/kotlin/gradle/gradle-java:kotlin.gradle.gradle-java[module]",
        "//intellij-community/plugins/kotlin/base/project-structure:kotlin.base.project-structure[module]",
    ],
)
