load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.java.ide.resources",
    iml_files = ["intellij.java.ide.resources.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    resources = ["resources"],
    visibility = ["//visibility:public"],
    runtime_deps = ["//intellij-community/platform/platform-resources:intellij.platform.resources"],
)
