load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.platform.resources",
    iml_files = ["intellij.platform.resources.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    resources = ["src"],
    visibility = ["//visibility:public"],
    runtime_deps = ["//intellij-community/platform/util:intellij.platform.util"],
)
