load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.python.dataVision",
    srcs = ["src"],
    iml_files = ["intellij.python.dataVision.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    visibility = ["//visibility:public"],
    deps = ["//intellij-community:kotlin-stdlib"],
)
