load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.java.compiler.instrumentationUtil.java8",
    srcs = ["src"],
    iml_files = ["intellij.java.compiler.instrumentationUtil.java8.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    jvm_target = "8",
    visibility = ["//visibility:public"],
    deps = ["//intellij-community/java/compiler/instrumentation-util:intellij.java.compiler.instrumentationUtil[module]"],
)
