load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.javaFX.common",
    srcs = ["src"],
    iml_files = ["intellij.javaFX.common.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    jvm_target = "11",
    resources = ["resources"],
    visibility = ["//visibility:public"],
    deps = ["//intellij-community/platform/util:intellij.platform.util[module]"],
)
