load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.tools.ide.util.common",
    srcs = ["src"],
    iml_files = ["intellij.tools.ide.util.common.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "//intellij-community:kotlinx-coroutines-core",
        "//intellij-community:kotlin-stdlib",
    ],
)
