load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.java.compiler.instrumentationUtil",
    srcs = ["src"],
    iml_files = ["intellij.java.compiler.instrumentationUtil.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    jvm_target = "7",
    visibility = ["//visibility:public"],
    deps = ["//intellij-community:ASM"],
)
