load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "kotlin.compiler-plugins.kotlinx-serialization.gradle",
    srcs = ["src"],
    iml_files = ["kotlin.compiler-plugins.kotlinx-serialization.gradle.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    resources = ["resources"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "//intellij-community:kotlin-stdlib",
        "//intellij-community/plugins/kotlin/base/facet:kotlin.base.facet[module]",
        "//intellij-community/plugins/kotlin/core:kotlin.core[module]",
        "//intellij-community/plugins/kotlin/gradle/gradle-java:kotlin.gradle.gradle-java[module]",
        "//intellij-community/plugins/kotlin/compiler-plugins/kotlinx-serialization/common:kotlin.compiler-plugins.kotlinx-serialization.common[module]",
        "//intellij-community/plugins/gradle:intellij.gradle.common[module]",
    ],
)
