load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.platform.core.nio.fs",
    srcs = ["src"],
    iml_files = ["intellij.platform.core.nio.fs.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    jvm_target = "8",
    visibility = ["//visibility:public"],
    deps = ["//intellij-community/platform/util:intellij.platform.util[module]"],
)
