load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "kotlin.code-insight.inspections-shared.tests.k1",
    iml_files = ["kotlin.code-insight.inspections-shared.tests.k1.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    test_srcs = ["test"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "//intellij-community/plugins/kotlin/plugin/k1:kotlin.plugin.k1[module, test]",
        "//intellij-community:kotlin-stdlib[test]",
        "//intellij-community:kotlinc.high-level-api[test]",
        "//intellij-community:kotlinc.kotlin-compiler-common[test]",
        "//intellij-community:kotlin-reflect[test]",
        "//intellij-community:kotlinc.kotlin-compiler-tests[test]",
        "//intellij-community/plugins/kotlin/base/util:kotlin.base.util[module, test]",
        "//intellij-community/plugins/kotlin/base/psi:kotlin.base.psi[module, test]",
        "//intellij-community/plugins/kotlin/base/resources:kotlin.base.resources[module, test]",
        "//intellij-community/plugins/kotlin/base/code-insight:kotlin.base.code-insight[module, test]",
        "//intellij-community/plugins/kotlin/base/fe10/plugin:kotlin.base.fe10.plugin[module, test]",
        "//intellij-community/plugins/kotlin/code-insight/api:kotlin.code-insight.api[module, test]",
        "//intellij-community/plugins/kotlin/code-insight/utils:kotlin.code-insight.utils[module, test]",
        "//intellij-community/plugins/kotlin/code-insight/inspections-shared:kotlin.code-insight.inspections-shared[module, test]",
        "//intellij-community/plugins/kotlin/idea/tests:kotlin.idea.tests[module, test]",
        "//intellij-community/plugins/kotlin/tests-common:kotlin.tests-common[module, test]",
        "//intellij-community/platform/core-impl:intellij.platform.core.impl[module, test]",
        "//intellij-community/platform/analysis-api:intellij.platform.analysis[module, test]",
        "//intellij-community/platform/editor-ui-api:intellij.platform.editor[module, test]",
        "//intellij-community/platform/lang-api:intellij.platform.lang[module, test]",
        "//intellij-community/java/java-psi-api:intellij.java.psi[module, test]",
    ],
)
