load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.platform.indexing.tests",
    iml_files = ["intellij.platform.indexing.tests.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    test_srcs = ["testSrc"],
    visibility = ["//visibility:public"],
    deps = ["//intellij-community/platform/testFramework:intellij.platform.testFramework[module, test]"],
)
