load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "kotlin.base.fe10.analysis",
    srcs = ["src"],
    iml_files = ["kotlin.base.fe10.analysis.iml"],
    javacopts_from_jps = ["-Xlint:unchecked"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "//intellij-community:kotlin-stdlib",
        "//intellij-community:kotlinc.kotlin-compiler-common",
        "//intellij-community:kotlinc.kotlin-compiler-fe10",
        "//intellij-community:kotlinc.kotlin-compiler-ir",
        "//intellij-community:kotlinc.kotlin-jps-common",
        "//intellij-community:kotlinc.kotlin-scripting-compiler-impl",
        "//intellij-community:kotlinc.high-level-api",
        "//intellij-community:kotlinc.high-level-api-fe10",
        "//intellij-community:kotlinc.analysis-project-structure",
        "//intellij-community:Guava",
        "//intellij-community:javaslang",
        "//intellij-community:javax-inject",
        "//intellij-community/plugins/kotlin/base/util:kotlin.base.util[module]",
        "//intellij-community/plugins/kotlin/base/psi:kotlin.base.psi[module]",
        "//intellij-community/plugins/kotlin/base/facet:kotlin.base.facet[module]",
        "//intellij-community/plugins/kotlin/base/indices:kotlin.base.indices[module]",
        "//intellij-community/plugins/kotlin/base/project-structure:kotlin.base.project-structure[module]",
        "//intellij-community/plugins/kotlin/base/scripting:kotlin.base.scripting[module]",
        "//intellij-community/plugins/kotlin/base/analysis:kotlin.base.analysis[module]",
        "//intellij-community/platform/core-impl:intellij.platform.core.impl[module]",
        "//intellij-community/platform/editor-ui-api:intellij.platform.editor[module]",
        "//intellij-community/platform/core-ui:intellij.platform.core.ui[module]",
        "//intellij-community/java/java-impl:intellij.java.impl[module]",
        "//intellij-community/java/openapi:intellij.java[module]",
        "//intellij-community/java/java-analysis-api:intellij.java.analysis[module]",
    ],
)
